version: '3.8'

services:
  pgdb:
    image : docker.arvancloud.ir/postgres:14.1-alpine
    container_name: pgdb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes: 
      - postgres-data:/var/lib/postgresql


volumes:
    postgres-data: